### ISSUE TITLE
Suggestion: Replace all "#" symbols in file paths

### ISSUE THREAD

**Issue by alters-mit** [Learning-and-Intelligent-Systems/kitchen-worlds#1]
`#` is surprisingly difficult to handle in a Windows file path; this repo can't be cloned in Windows without WSL. There may be additional problems with basic curl/wget requests that I haven't tried.

**Comment by zt-yang** [comment]
That's a good point. Thank you for pointing it out. # is used when indexing multiple objects of the same object assets, which is replaced to be % when I generate image files. May I know where else do you find # still used in file names?

**Comment by zt-yang** [comment]
Got it. That data generation pipeline has since been modified so the problems won't happen again
