### ISSUE TITLE
`range` link is commented out

### ISSUE THREAD

**Issue by alters-mit** [Learning-and-Intelligent-Systems/kitchen-worlds#3]
[All or most of the stove-top range links and joints are commented out in this .urdf file.](https://github.com/zt-yang/kitchen-models/blob/63a387669ce89cf2800f65d38f52c5694b24c156/counter/urdf/kitchen_part_right_gen_convex.urdf)

**Comment by zt-yang** [comment]
Are you referring to `models/Oven/01909/mobility.urdf? If you want the original URDFs, they are modified from the [PartNet-Mobility dataset](https://sapien.ucsd.edu/browse) of articulated objects. I kept multiple versions of the joints in the urdf for testing.
