### ISSUE TITLE
No "output" and "test_cases" directories

### ISSUE THREAD

**Issue by threefruits** [Learning-and-Intelligent-Systems/kitchen-worlds#6]
Hello!

I am trying to use the library but faced some problems. I would be glad if you could provide some guidance. 

Can you please advise me on how to generate the "output" and "test_cases" directories? It seems that all the test codes are based on the "output" and "test_cases" directories. And I also can't generate any scenes using test_world_builder.py.

Thank you very much in advance!

**Comment by zt-yang** [comment]
Thank you for trying out the codes! The problem with running `test_world_builder.py` should have been fixed now, see updated README. for `outputs` and `test_cases` you can just `mkdir outputs` as they are just output directories now.
